---
# This playbook knows how to install postgres and its related extensions on Ubuntu

- hosts: all
  become_method: sudo
  roles:
    - { role: packages_ubuntu }
    - { role: postgres}
    - { role: DavidWittman.redis }
    #Uncomment if you want to install pgtap too:
    #- { role: pgtap}
